# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # CLI / dev tool output (bin/thpitze_core.dart)
    avoid_print: false

    # app/main_window.dart (return in finally)
    control_flow_in_finally: false

    # doc comments containing `<vaultRoot>/...`
    unintended_html_in_doc_comment: false

    # stylistic
    unnecessary_underscores: false
    use_super_parameters: false
